name: tfg_cco
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  brasil_fields: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  get: 4.3.8
  get_storage: 2.0.3
  json_annotation: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  validatorless: ^1.2.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.1
  json_serializable: ^4.1.1
  lints: 1.0.1

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/marcas/

